# Generated by Django 3.1.1 on 2022-01-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
    ]
