# Generated by Django 4.0 on 2021-12-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Programming language name')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Operator name')),
                ('num_of_operands', models.PositiveIntegerField(verbose_name='Number of operands')),
                ('syntax', models.CharField(max_length=256, verbose_name='Operator syntax')),
                ('prog_lang', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='operators', to='operators.programminglanguage')),
            ],
        ),
    ]
